s = {}
name = input("Enter friends name :")
language = input("Enter Language name :")
s.update({name : language})
name = input("Enter friends name :")
language = input("Enter Language name :")
s.update({name : language})
name = input("Enter friends name :")
language = input("Enter Language name :")
s.update({name : language})
name = input("Enter friends name :")
language = input("Enter Language name :")
s.update({name : language})
name = input("Enter friends name :")
language = input("Enter Language name :")
s.update({name : language})

print(s)